### ISSUE TITLE
Slider doesn't work on Firefox for Android

### ISSUE THREAD

**Issue by gShahar** [yuvadm/geshem.space#27]
(It does work on Chrome)

**Comment by yuvadm** [comment]
Thanks for the report @gShahar any chance you can help me debug this?

**Comment by gShahar** [comment]
Sorry, I have zero exprience in debugging webpages, though I'd be happy to help. Mabye you can direct me to a manual for this issue?
I already managed my way to the debugger (after connecting the phone using the USB).

**Comment by yuvadm** [comment]
Let's start from the basics, do you see any errors in the Javascript console?

**Comment by gShahar** [comment]
yes, as follows (not sure if relevant):

09:59:37.336 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://events.mapbox.com/events/v2?access_token=pk.eyJ1IjoieXV2YWRtIiwiYSI6ImNpcnMxbzBuaTAwZWdoa25oczlzZmkwbHcifQ.UHtLngbKm9O8945pJm23Nw. (Reason: CORS request did not succeed).

**Comment by yuvadm** [comment]
Do you have any script blockers enabled? Regardless, that specific error doesn't seem to be the problem in this case.

**Comment by gShahar** [comment]
Yes, now disabled. no other errors on the console.
