### ISSUE TITLE
Differences from the IMS map

### ISSUE THREAD

**Issue by niryariv** [yuvadm/geshem.space#8]
I just discovered this project and I love it. It seems like there's something off in importing data from the IMS radar site. 

Geshem is currently reporting scattered rains around Modiin, but it's a clear day, as 
reflected in the IMS map:

<img width="545" alt="screen shot 2017-11-26 at 10 50 38 am" src="https://user-images.githubusercontent.com/1771/33238518-2a44d90e-d298-11e7-959b-402de478d9c9.png">

<img width="516" alt="screen shot 2017-11-26 at 10 50 59 am" src="https://user-images.githubusercontent.com/1771/33238517-2a03ebce-d298-11e7-82fb-a39078be1863.png">

**Comment by yuvadm** [comment]
@niryariv thanks for the feedback! What you're seeing there is radar noise in the original radar imagery which also comes from the IMS.

I have no idea why this imagery is noisy while the other is not, but note that the version I use is a transparent PNG and the second version already has a base layer that is not easily removable (unless you do some pixel subtraction or something), and even then it has a lower resolution.

Happy to hear your thoughts if there's any way you think we can clean up the images :)

**Comment by yuvadm** [comment]
This issue has become stale since we're using the new combined data overlays which are much cleaner
