### ISSUE TITLE
Geshem seems to be always one slide behind

### ISSUE THREAD

**Issue by barboaz** [yuvadm/geshem.space#9]
If it's 11:17, the last slide in geshem is from 10:50, while the last one in the MAKAM GESHEM site is from 11:00.

**Comment by yuvadm** [comment]
@barboaz Hmm.. "always"? The cron job runs every minute, so unless you fall right on the minute after an update, there shouldn't be a diff. Right now I see 12:20 on Geshem and 10:20 on the source JSON (note the use of GMT in the source) so they seem to be synced. Does this rule out a off-by-one error or do you think there's something else going on?

**Comment by barboaz** [comment]
@yuvadm I'm not sure what is the reason but http://www.ims.gov.il/IMS/tazpiot/RainRadar.htm **always** seems to be 10 minutes ahead of geshem.space.

**Comment by yuvadm** [comment]
Note that the radar you linked to is different than the one I use (which originates from http://map.govmap.gov.il/rainradar/radar.json and has transparent PNGs).

Those are two different sets of images that are possibly generated at different times.

**Comment by barboaz** [comment]
Oh, ok. It seems to be up to 23 minutes late (the other one is up to 16 minutes late).

**Comment by yuvadm** [comment]
Since we now have access to the main FTP server, there shouldn't be any delays other than those caused at the origin (~15-18 minutes seems to be the standard..)
